### ISSUE TITLE
Use local resources

### ISSUE THREAD

**Issue by cjessett** [SiliconSurfer13/prj-rev-bwfs-dasmoto#2]
(Important) [Here](https://github.com/SiliconSurfer13/prj-rev-bwfs-dasmoto/blob/1e9dd8134c6ac915697abed86e8b54938634516b/Dasmotos/index.html#L19) you should download this image and include it in your local resources then link to your local version in  case the url is unreachable.

**Comment by SiliconSurfer13** [comment]
Will do so for future projects. Thanks!
