### ISSUE TITLE
Prefer id attribute for single use styles

### ISSUE THREAD

**Issue by cjessett** [SiliconSurfer13/prj-rev-bwfs-dasmoto#3]
(Subtlety) Instead of using the `class` attribute for [this styling](https://github.com/SiliconSurfer13/prj-rev-bwfs-dasmoto/blob/1e9dd8134c6ac915697abed86e8b54938634516b/Dasmotos/resources/css/style.css#L19) you should use the `id` attribute. Then you would select it in your css with `#brushes`

**Comment by SiliconSurfer13** [comment]
Got It!
