### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [SiliconSurfer13/prj-rev-bwfs-dasmoto#4]
(Meets Expectations) Overall, well done.

Remember to prefer the `id` attribute for single use styles. Also, remember to only use local resources; in case a url becomes unreachable your page will remain unchanged.

Again, nice use of comments and empty lines in your html. Your code is clean and easy to follow. Nice job!

**Comment by SiliconSurfer13** [comment]
I was going to ask about that. I thought about downloading the image files into the resources folder, but since we hadn't really been doing that in any of the exercises I opted to use the URL's I was going to do 1/2 & 1/2 just to show I know how to do that but forgot!
